name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start PostgreSQL on Ubuntu
      run: |
        sudo systemctl start postgresql.service
        pg_isready
    
    - name: Create additional user
      run: |
        sudo -u postgres psql --command="CREATE USER testuser PASSWORD 'password'" --command="\du"
    
    - name: Create additional database
      run: |
        sudo -u postgres createdb --owner=testuser TestDatabase
        PGPASSWORD=password psql --username=testuser --host=localhost --list timetable
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
